import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <p className='text-[#ff0] p-[10px] border'>
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. 
        Nisi nemo ratione praesentium debitis nam consequuntur 
        tempora blanditiis quisquam molestias tenetur!
      </p>
    </>
  )
}
